using System;
using System.Collections.Generic;
using System.Globalization;

/// <summary>
/// Guarded preferred[] provider for the source-path replay.
///
/// v0.9.15 modeled subset:
/// - deterministic 0x2E97 rotate tuples are generated and used;
/// - visible / safe 0x477D BFS/chase overrides are generated from the source
///   0x45DC coordinate-to-0x6200 guidance path;
/// - 0x2EC7 random base tuples can either stay trace-synced for exact MAME
///   comparison or be generated from a seeded C# Random for behavior testing.
///
/// In CSharpSeeded mode, the branch timing is still inferred from the reference
/// trace family, but the random tuple content is generated by the C# candidate.
/// This is intentional: it lets the left board behave like a real simulation
/// without trying to reproduce the Z80 R register exactly.
/// </summary>
public static class LadyBugPreferredHybridProvider
{
    public sealed class Context
    {
        private readonly Random _random;

        public Context(LadyBugEnemySimulationSettings settings)
        {
            Settings = settings ?? new LadyBugEnemySimulationSettings();
            _random = new Random(Settings.CSharpRandomSeed);
        }

        public LadyBugEnemySimulationSettings Settings { get; }

        public int NextRandomRLow()
        {
            return _random.Next(0, 16) & 0x0F;
        }
    }

    public static bool TryGetPreferred(EnemyTraceFrame frame, int activeSlot, out Result result)
    {
        var context = new Context(LadyBugEnemySimulationSettings.LoadOrDefault());
        return TryGetPreferred(context, null, frame, activeSlot, -1, -1, out result);
    }

    public static bool TryGetPreferred(
        Context context,
        EnemyTraceFrame? sourceFrame,
        EnemyTraceFrame resultFrame,
        int activeSlot,
        int sourceEnemyX,
        int sourceEnemyY,
        out Result result)
    {
        result = Result.Missing(activeSlot);
        context ??= new Context(LadyBugEnemySimulationSettings.LoadOrDefault());

        if (!TryCopyReferencePreferredTuple(resultFrame, out int[] referenceTuple))
            return false;

        if (activeSlot < 0 || activeSlot >= LadyBugMonsterPreferenceSystem.PreferredSlotCount)
            return false;

        if (!IsOneHotDirection(referenceTuple[activeSlot]))
            return false;

        LadyBugBfsChaseSourceModel.GuidanceResult guidance = default;
        bool hasBfsGuidance =
            sourceFrame != null &&
            sourceEnemyX >= 0 &&
            sourceEnemyY >= 0 &&
            IsChaseTimerActive(resultFrame, activeSlot) &&
            LadyBugBfsChaseSourceModel.TryGetGuidance(
                sourceFrame,
                sourceEnemyX,
                sourceEnemyY,
                out guidance);

        if (TryGetPlayerDirection(resultFrame, out int playerDirection))
        {
            int[] rotateTuple = LadyBugMonsterPreferenceSystem.GenerateRotateBranch(playerDirection);

            if (LadyBugMonsterPreferenceSystem.TupleEquals(rotateTuple, referenceTuple))
            {
                result = Result.ModeledRotate(activeSlot, rotateTuple, playerDirection);
                return true;
            }

            if (hasBfsGuidance &&
                TryBuildVisibleBfsOverrideResultFromBase(
                    activeSlot,
                    referenceTuple,
                    rotateTuple,
                    "2E97_ROTATE_FROM_" + Hex2(playerDirection),
                    guidance,
                    out result))
            {
                return true;
            }
        }

        if (context.Settings.UsesCSharpRandom)
        {
            int rLow = context.NextRandomRLow();
            int[] randomTuple = LadyBugMonsterPreferenceSystem.GenerateRandomBranchFromUsedRLow(rLow);
            string source = "2EC7_CSHARP_RANDOM_RLOW_" + rLow.ToString("X1", CultureInfo.InvariantCulture);

            if (hasBfsGuidance && IsOneHotDirection(guidance.Direction))
            {
                int[] withBfs = CopyTuple(randomTuple);
                withBfs[activeSlot] = guidance.Direction & 0x0F;
                result = Result.ModeledCSharpRandomWithBfs(activeSlot, withBfs, source, guidance);
                return true;
            }

            result = Result.ModeledCSharpRandom(activeSlot, randomTuple, source);
            return true;
        }

        if (hasBfsGuidance &&
            TryBuildVisibleBfsOverrideResult(
                resultFrame,
                activeSlot,
                referenceTuple,
                guidance,
                out result))
        {
            return true;
        }

        result = Result.TraceFallback(activeSlot, referenceTuple, "trace-sync-random-or-bfs-or-unmatched-rotate");
        return true;
    }

    private static bool TryBuildVisibleBfsOverrideResult(
        EnemyTraceFrame resultFrame,
        int activeSlot,
        int[] referenceTuple,
        LadyBugBfsChaseSourceModel.GuidanceResult guidance,
        out Result result)
    {
        result = Result.Missing(activeSlot);

        foreach (BaseCandidate candidate in EnumerateBaseCandidates(resultFrame))
        {
            if (TryBuildVisibleBfsOverrideResultFromBase(
                    activeSlot,
                    referenceTuple,
                    candidate.Tuple,
                    candidate.Source,
                    guidance,
                    out result))
            {
                return true;
            }
        }

        return false;
    }

    private static bool TryBuildVisibleBfsOverrideResultFromBase(
        int activeSlot,
        int[] referenceTuple,
        int[] baseTuple,
        string baseSource,
        LadyBugBfsChaseSourceModel.GuidanceResult guidance,
        out Result result)
    {
        result = Result.Missing(activeSlot);
        int overrideDirection = guidance.Direction & 0x0F;

        if (!IsOneHotDirection(overrideDirection))
            return false;

        if ((referenceTuple[activeSlot] & 0x0F) != overrideDirection)
            return false;

        if (!IsVisibleOverrideOverBase(referenceTuple, baseTuple, activeSlot))
            return false;

        int[] modeled = CopyTuple(baseTuple);
        modeled[activeSlot] = overrideDirection;

        if (!LadyBugMonsterPreferenceSystem.TupleEquals(modeled, referenceTuple))
            return false;

        result = Result.ModeledBfs(activeSlot, modeled, baseSource, guidance);
        return true;
    }

    private static IEnumerable<BaseCandidate> EnumerateBaseCandidates(EnemyTraceFrame resultFrame)
    {
        if (TryGetPlayerDirection(resultFrame, out int playerDirection))
        {
            yield return new BaseCandidate(
                LadyBugMonsterPreferenceSystem.GenerateRotateBranch(playerDirection),
                "2E97_ROTATE_FROM_" + Hex2(playerDirection));
        }

        for (int rLow = 0; rLow < 16; rLow++)
        {
            yield return new BaseCandidate(
                LadyBugMonsterPreferenceSystem.GenerateRandomBranchFromUsedRLow(rLow),
                "2EC7_RANDOM_RLOW_" + rLow.ToString("X1", CultureInfo.InvariantCulture));
        }
    }

    private static bool IsVisibleOverrideOverBase(int[] referenceTuple, int[] baseTuple, int activeSlot)
    {
        if (activeSlot < 0 || activeSlot >= LadyBugMonsterPreferenceSystem.PreferredSlotCount)
            return false;

        for (int i = 0; i < LadyBugMonsterPreferenceSystem.PreferredSlotCount; i++)
        {
            if (i == activeSlot)
                continue;

            if ((referenceTuple[i] & 0x0F) != (baseTuple[i] & 0x0F))
                return false;
        }

        return (referenceTuple[activeSlot] & 0x0F) != (baseTuple[activeSlot] & 0x0F);
    }

    private static bool IsChaseTimerActive(EnemyTraceFrame frame, int activeSlot)
    {
        if (frame.enemyWork?.chaseTimers == null ||
            activeSlot < 0 ||
            activeSlot >= frame.enemyWork.chaseTimers.Count)
        {
            return false;
        }

        return (frame.enemyWork.chaseTimers[activeSlot] & 0xFF) != 0;
    }

    private static bool TryCopyReferencePreferredTuple(EnemyTraceFrame frame, out int[] tuple)
    {
        tuple = new int[LadyBugMonsterPreferenceSystem.PreferredSlotCount];

        if (frame.enemyWork == null ||
            frame.enemyWork.preferred == null ||
            frame.enemyWork.preferred.Count < LadyBugMonsterPreferenceSystem.PreferredSlotCount)
        {
            return false;
        }

        for (int i = 0; i < tuple.Length; i++)
            tuple[i] = frame.enemyWork.preferred[i] & 0x0F;

        return true;
    }

    private static bool TryGetPlayerDirection(EnemyTraceFrame frame, out int direction)
    {
        direction = 0;

        if (frame.player == null)
            return false;

        if (TryParseDirectionText(frame.player.dir, out direction))
            return true;

        direction = DirectionFromRaw(frame.player.raw);
        return IsOneHotDirection(direction);
    }

    private static bool TryParseDirectionText(string? text, out int direction)
    {
        direction = 0;

        if (string.IsNullOrWhiteSpace(text))
            return false;

        string trimmed = text.Trim();
        if (trimmed.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
            trimmed = trimmed.Substring(2);

        if (!int.TryParse(trimmed, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out int value))
            return false;

        direction = value & 0x0F;
        return IsOneHotDirection(direction);
    }

    private static int DirectionFromRaw(int raw)
    {
        return raw < 0 ? 0 : (raw >> 4) & 0x0F;
    }

    private static bool IsOneHotDirection(int direction)
    {
        int d = direction & 0x0F;
        return d == LadyBugMonsterPreferenceSystem.DirLeft ||
               d == LadyBugMonsterPreferenceSystem.DirUp ||
               d == LadyBugMonsterPreferenceSystem.DirRight ||
               d == LadyBugMonsterPreferenceSystem.DirDown;
    }

    private static int[] CopyTuple(IReadOnlyList<int> values)
    {
        var tuple = new int[LadyBugMonsterPreferenceSystem.PreferredSlotCount];
        for (int i = 0; i < tuple.Length && i < values.Count; i++)
            tuple[i] = values[i] & 0x0F;
        return tuple;
    }

    private static string Hex2(int value)
    {
        return (value & 0xFF).ToString("X2", CultureInfo.InvariantCulture);
    }

    private readonly struct BaseCandidate
    {
        public BaseCandidate(int[] tuple, string source)
        {
            Tuple = tuple;
            Source = source;
        }

        public int[] Tuple { get; }
        public string Source { get; }
    }

    public readonly struct Result
    {
        private Result(
            int activeSlot,
            int[] preferredTuple,
            bool usedModeledRotate,
            bool usedModeledBfs,
            bool usedModeledCSharpRandom,
            bool usedTraceFallback,
            string source,
            string guidance)
        {
            ActiveSlot = activeSlot;
            PreferredTuple = preferredTuple;
            UsedModeledRotate = usedModeledRotate;
            UsedModeledBfs = usedModeledBfs;
            UsedModeledCSharpRandom = usedModeledCSharpRandom;
            UsedTraceFallback = usedTraceFallback;
            Source = source;
            Guidance = guidance;
        }

        public int ActiveSlot { get; }
        public int[] PreferredTuple { get; }
        public bool UsedModeledRotate { get; }
        public bool UsedModeledBfs { get; }
        public bool UsedModeledCSharpRandom { get; }
        public bool UsedTraceFallback { get; }
        public string Source { get; }
        public string Guidance { get; }

        public int Preferred =>
            ActiveSlot >= 0 && ActiveSlot < PreferredTuple.Length
                ? PreferredTuple[ActiveSlot] & 0x0F
                : 0;

        public static Result Missing(int activeSlot)
        {
            return new Result(activeSlot, new int[LadyBugMonsterPreferenceSystem.PreferredSlotCount], false, false, false, true, "missing", string.Empty);
        }

        public static Result ModeledRotate(int activeSlot, int[] preferredTuple, int playerDirection)
        {
            return new Result(
                activeSlot,
                CopyTuple(preferredTuple),
                true,
                false,
                false,
                false,
                "2E97_MODELED_ROTATE_FROM_" + Hex2(playerDirection),
                string.Empty);
        }

        public static Result ModeledBfs(
            int activeSlot,
            int[] preferredTuple,
            string baseSource,
            LadyBugBfsChaseSourceModel.GuidanceResult guidance)
        {
            return new Result(
                activeSlot,
                CopyTuple(preferredTuple),
                false,
                true,
                false,
                false,
                "477D_MODELED_BFS_OVER_" + baseSource,
                guidance.ToCompactString());
        }

        public static Result ModeledCSharpRandom(int activeSlot, int[] preferredTuple, string source)
        {
            return new Result(
                activeSlot,
                CopyTuple(preferredTuple),
                false,
                false,
                true,
                false,
                source,
                string.Empty);
        }

        public static Result ModeledCSharpRandomWithBfs(
            int activeSlot,
            int[] preferredTuple,
            string randomSource,
            LadyBugBfsChaseSourceModel.GuidanceResult guidance)
        {
            return new Result(
                activeSlot,
                CopyTuple(preferredTuple),
                false,
                true,
                true,
                false,
                "477D_MODELED_BFS_OVER_" + randomSource,
                guidance.ToCompactString());
        }

        public static Result TraceFallback(int activeSlot, int[] preferredTuple, string source)
        {
            return new Result(activeSlot, CopyTuple(preferredTuple), false, false, false, true, source, string.Empty);
        }
    }
}
