-- ladybug_sequence_v8_trace.lua
--
-- MAME Lua helper for Lady Bug sequence tracing.
-- v8: same trace logic as v7, but supports an external runtime config file generated by the Windows wrapper.
--
-- Goal:
--   1. Start MAME.
--   2. Request loading a save-state, usually "test1" (not "test1.sta").
--   3. Use emu.add_machine_post_load_notifier so tick 0 is captured immediately
--      after the save-state has actually been restored.
--   4. Capture a frame-by-frame JSONL trace after tick 0.
--
-- Suggested launch:
--   run_ladybug_sequence_v8.bat
--
-- Outputs:
--   ladybug_sequence_v8_initial_snapshot.json
--   ladybug_sequence_v8_trace.jsonl
--   ladybug_sequence_v8_summary.txt
--
-- Important:
--   The first line of *_trace.jsonl is tick 0 and is captured from the
--   post-load notifier. It is not captured after an arbitrary 90-frame delay.

local CONFIG = {
    output_prefix = "ladybug_sequence_v8",
    output_dir = ".",

    save_state = "test1",
    load_after_frames = 5,

    -- Number of emulated frames to capture AFTER tick 0.
    -- Total JSONL lines = frames_after_tick0_to_capture + 1.
    frames_after_tick0_to_capture = 600,

    exit_when_done = true,
    pause_when_done = false,

    -- For Windows/debugging: keep files readable while MAME is still running.
    flush_every_trace_line = true,

    -- Usually keep this false. Initial snapshot already includes full VRAM/RAM.
    include_full_memory_each_frame = false,

    -- Useful for comparing enemy logic. This is only 0xB0 bytes per frame.
    include_logical_maze_each_frame = true,

    door_vram_table = 0x0D1D,
    door_nav_index_table = 0x46C4,
    door_count = 20,

    vram_gate_base = 0xD080,
    vram_column_stride = 0x20,

    tile_horizontal = 0x36,
    tile_vertical = 0x3E,
}


-- Optional runtime config generated by run_ladybug_sequence_v8.bat.
-- The file must return a Lua table, for example:
-- return { save_state = "test1", frames_after_tick0_to_capture = 600 }
local function merge_runtime_config()
    local cfg_path = "ladybug_sequence_runtime_config.lua"
    local f = io.open(cfg_path, "r")
    if not f then
        return
    end
    f:close()

    local ok, user_cfg = pcall(dofile, cfg_path)
    if not ok then
        emu.print_warning("Lady Bug sequence v8: could not load " .. cfg_path .. ": " .. tostring(user_cfg))
        return
    end

    if type(user_cfg) ~= "table" then
        emu.print_warning("Lady Bug sequence v8: " .. cfg_path .. " did not return a table")
        return
    end

    for k, v in pairs(user_cfg) do
        CONFIG[k] = v
    end

    emu.print_info("Lady Bug sequence v8: loaded runtime config from " .. cfg_path)
end

merge_runtime_config()

-- Godot gate definitions copied from scenes/level/Level.tscn.
-- These ids are your Godot GateId values, not the arcade door-table order.
local GATES = {
    { id =  0, x =  2, y =  1, initial = "Horizontal" },
    { id =  1, x =  9, y =  1, initial = "Horizontal" },
    { id =  2, x =  4, y =  2, initial = "Horizontal" },
    { id =  3, x =  7, y =  2, initial = "Horizontal" },
    { id =  4, x =  1, y =  3, initial = "Vertical"   },
    { id =  5, x =  3, y =  3, initial = "Horizontal" },
    { id =  6, x =  8, y =  3, initial = "Horizontal" },
    { id =  7, x = 10, y =  3, initial = "Vertical"   },
    { id =  8, x =  4, y =  4, initial = "Horizontal" },
    { id =  9, x =  7, y =  4, initial = "Horizontal" },
    { id = 10, x =  3, y =  6, initial = "Vertical"   },
    { id = 11, x =  8, y =  6, initial = "Vertical"   },
    { id = 12, x =  2, y =  7, initial = "Vertical"   },
    { id = 13, x =  4, y =  7, initial = "Vertical"   },
    { id = 14, x =  7, y =  7, initial = "Vertical"   },
    { id = 15, x =  9, y =  7, initial = "Vertical"   },
    { id = 16, x =  4, y =  9, initial = "Horizontal" },
    { id = 17, x =  7, y =  9, initial = "Horizontal" },
    { id = 18, x =  2, y = 10, initial = "Horizontal" },
    { id = 19, x =  9, y = 10, initial = "Horizontal" },
}

local function pivot_key(x, y)
    return string.format("%d,%d", math.floor(x), math.floor(y))
end

local GATES_BY_PIVOT = {}
for _, g in ipairs(GATES) do
    GATES_BY_PIVOT[pivot_key(g.x, g.y)] = g
end

local cpu = nil
local mem = nil
local trace_file = nil
local snapshot_file = nil
local summary_file = nil

local initialized = false
local load_requested = false
local load_call_ok = nil
local load_call_error = ""
local post_load_seen = false
local capture_started = false
local done = false

local mame_frame = 0
local frames_since_load_request = 0
local frames_after_tick0_written = 0
local trace_lines_written = 0
local capture_origin = ""
local post_load_subscription = nil
local reset_subscription = nil
local frame_subscription = nil

local function h2(v) return string.format("%02X", v & 0xff) end
local function h4(v) return string.format("%04X", v & 0xffff) end
local function boolstr(v) return v and "true" or "false" end

local function escape_json(s)
    s = tostring(s or "")
    s = s:gsub('\\', '\\\\')
         :gsub('"', '\\"')
         :gsub('\b', '\\b')
         :gsub('\f', '\\f')
         :gsub('\n', '\\n')
         :gsub('\r', '\\r')
         :gsub('\t', '\\t')
    return s
end

local function q(s) return '"' .. escape_json(s) .. '"' end
local function arr(items) return "[" .. table.concat(items, ",") .. "]" end
local function obj(items) return "{" .. table.concat(items, ",") .. "}" end

local function log_error(message)
    if emu ~= nil and emu.print_error ~= nil then
        pcall(function() emu.print_error(message) end)
    else
        print(message)
    end
end

local function read_u8(addr) return mem:read_u8(addr) & 0xff end
local function read_u16_le(addr) return read_u8(addr) + (read_u8(addr + 1) << 8) end

local function read_range_hex(start_addr, length)
    local out = {}
    for i = 0, length - 1 do
        out[#out + 1] = h2(read_u8(start_addr + i))
    end
    return table.concat(out, "")
end

local function get_program_space()
    cpu = manager.machine.devices[":maincpu"]
    if cpu == nil then error("Cannot find device :maincpu") end
    mem = cpu.spaces["program"]
    if mem == nil then error("Cannot find :maincpu program address space") end
end

local function state_value(names)
    if cpu == nil or cpu.state == nil then return nil end
    for _, name in ipairs(names) do
        local item = cpu.state[name]
        if item ~= nil then return item.value end
    end
    return nil
end

local function state_hex(names, digits)
    local v = state_value(names)
    if v == nil then return "" end
    if digits == 2 then return h2(v) end
    return h4(v)
end

local function output_path(suffix)
    local dir = CONFIG.output_dir or "."
    if dir == "" or dir == "." then
        return CONFIG.output_prefix .. suffix
    end
    local last = dir:sub(-1)
    if last == "/" or last == "\\" then
        return dir .. CONFIG.output_prefix .. suffix
    end
    return dir .. "/" .. CONFIG.output_prefix .. suffix
end

local function must_open(path, mode)
    local f, err = io.open(path, mode)
    if f == nil then error("Cannot open output file: " .. tostring(path) .. " / " .. tostring(err)) end
    return f
end

local function open_outputs_if_needed()
    if trace_file ~= nil then return end
    trace_file = must_open(output_path("_trace.jsonl"), "w")
    snapshot_file = must_open(output_path("_initial_snapshot.json"), "w")
    summary_file = must_open(output_path("_summary.txt"), "w")
end

local function close_outputs()
    if trace_file ~= nil then trace_file:flush(); trace_file:close(); trace_file = nil end
    if snapshot_file ~= nil then snapshot_file:flush(); snapshot_file:close(); snapshot_file = nil end
    if summary_file ~= nil then summary_file:flush(); summary_file:close(); summary_file = nil end
end

local function classify_gate_tile(tile)
    if tile == CONFIG.tile_horizontal then return "Horizontal", "BlocksVertical", "Stable", "Exact" end
    if tile == CONFIG.tile_vertical   then return "Vertical",   "BlocksHorizontal", "Stable", "Exact" end
    if tile == 0x3F then return "Unknown", "Unknown", "TransitionOrLocalDoorCandidate", "DiagnosticOnly" end
    if tile == 0x49 then return "Unknown", "Unknown", "ForcedReversalTileCandidate", "DiagnosticOnly" end
    return "Unknown", "Unknown", "Unknown", "None"
end

local function arcade_addr_to_tile_xy(vram_addr)
    local off = vram_addr - CONFIG.vram_gate_base
    local column = math.floor(off / CONFIG.vram_column_stride)
    local row_from_bottom = off % CONFIG.vram_column_stride
    return column, row_from_bottom
end

local function arcade_addr_to_godot_pivot(vram_addr)
    local column, row_from_bottom = arcade_addr_to_tile_xy(vram_addr)
    local x_num = column - 1
    local y_num = 27 - row_from_bottom
    local integer_pivot = (x_num % 2 == 0) and (y_num % 2 == 0)
    local x = math.floor(x_num / 2)
    local y = math.floor(y_num / 2)
    return x, y, column, row_from_bottom, integer_pivot
end

local function nav_cell_json(addr)
    local v = read_u8(addr)
    return obj({
        q("address") .. ":" .. q(h4(addr)),
        q("value") .. ":" .. q(h2(v)),
        q("allowedHighNibble") .. ":" .. q(h2((v >> 4) & 0x0f)),
        q("bfsLowNibble") .. ":" .. q(h2(v & 0x0f))
    })
end

local function door_nav_probe_json(nav_addr)
    local addrs = { nav_addr, nav_addr - 1, nav_addr - 0x10, nav_addr - 0x0f }
    local out = {}
    for _, a in ipairs(addrs) do
        if a >= 0x6200 and a <= 0x62AF then out[#out + 1] = nav_cell_json(a) end
    end
    return arr(out)
end

local function arcade_entry(i)
    local vram_addr = read_u16_le(CONFIG.door_vram_table + i * 2)
    local tile = read_u8(vram_addr)
    local color = read_u8(vram_addr + 0x400)
    local orientation, logical_state, visual_state, confidence = classify_gate_tile(tile)
    local pivot_x, pivot_y, column, row_from_bottom, integer_pivot = arcade_addr_to_godot_pivot(vram_addr)
    local gate = nil
    if integer_pivot then gate = GATES_BY_PIVOT[pivot_key(pivot_x, pivot_y)] end
    local nav_index = read_u8(CONFIG.door_nav_index_table + i)
    local nav_addr = 0x6200 + nav_index

    return {
        arcade_index = i,
        gate = gate,
        pivot_x = pivot_x,
        pivot_y = pivot_y,
        column = column,
        row_from_bottom = row_from_bottom,
        integer_pivot = integer_pivot,
        vram_addr = vram_addr,
        tile = tile,
        color = color,
        orientation = orientation,
        logical_state = logical_state,
        visual_state = visual_state,
        confidence = confidence,
        nav_index = nav_index,
        nav_addr = nav_addr,
    }
end

local function build_entries_sorted_by_godot_id()
    local entries = {}
    for i = 0, CONFIG.door_count - 1 do entries[#entries + 1] = arcade_entry(i) end
    table.sort(entries, function(a, b)
        local aid = a.gate and a.gate.id or 999
        local bid = b.gate and b.gate.id or 999
        if aid == bid then return a.arcade_index < b.arcade_index end
        return aid < bid
    end)
    return entries
end

local function gate_short_json(e)
    local gate = e.gate
    local id = gate and gate.id or -1
    local initial = gate and gate.initial or "Unknown"
    return obj({
        q("id") .. ":" .. tostring(id),
        q("godotGateId") .. ":" .. tostring(id),
        q("arcadeDoorTableIndex") .. ":" .. tostring(e.arcade_index),
        q("pivot") .. ":" .. obj({ q("x") .. ":" .. tostring(e.pivot_x), q("y") .. ":" .. tostring(e.pivot_y) }),
        q("initialOrientation") .. ":" .. q(initial),
        q("currentOrientation") .. ":" .. q(e.orientation),
        q("logicalState") .. ":" .. q(e.logical_state),
        q("visualState") .. ":" .. q(e.visual_state),
        q("tile") .. ":" .. q(h2(e.tile)),
        q("color") .. ":" .. q(h2(e.color)),
        q("vramAddress") .. ":" .. q(h4(e.vram_addr)),
        q("navIndex") .. ":" .. q(h2(e.nav_index)),
        q("navBaseAddress") .. ":" .. q(h4(e.nav_addr)),
        q("orientationConfidence") .. ":" .. q(e.confidence)
    })
end

local function gates_json(include_nav_probe)
    local entries = build_entries_sorted_by_godot_id()
    local out = {}
    for _, e in ipairs(entries) do
        if include_nav_probe then
            local short = gate_short_json(e)
            -- Inject a small nav probe by removing final brace. Kept simple to avoid a huge per-frame trace.
            short = short:sub(1, -2) .. "," .. q("affectedNavigationCells6200") .. ":" .. door_nav_probe_json(e.nav_addr) .. "}"
            out[#out + 1] = short
        else
            out[#out + 1] = gate_short_json(e)
        end
    end
    return arr(out)
end

local function count_stable_gate_tiles()
    local stable, horizontal, vertical, unknown = 0, 0, 0, 0
    for i = 0, CONFIG.door_count - 1 do
        local addr = read_u16_le(CONFIG.door_vram_table + i * 2)
        local tile = read_u8(addr)
        if tile == CONFIG.tile_horizontal then stable = stable + 1; horizontal = horizontal + 1
        elseif tile == CONFIG.tile_vertical then stable = stable + 1; vertical = vertical + 1
        else unknown = unknown + 1 end
    end
    return stable, horizontal, vertical, unknown
end

local function mapping_diagnostics_json()
    local entries = build_entries_sorted_by_godot_id()
    local matched = 0
    local unmatched = 0
    local seen_ids = {}
    for _, e in ipairs(entries) do
        if e.gate ~= nil and e.integer_pivot then
            matched = matched + 1
            seen_ids[e.gate.id] = true
        else
            unmatched = unmatched + 1
        end
    end
    local missing = {}
    for _, g in ipairs(GATES) do
        if not seen_ids[g.id] then missing[#missing + 1] = tostring(g.id) end
    end
    return obj({
        q("matchedGodotGateCount") .. ":" .. tostring(matched),
        q("unmatchedArcadeDoorCount") .. ":" .. tostring(unmatched),
        q("missingGodotGateIds") .. ":" .. q(table.concat(missing, ","))
    })
end

local function likely_gameplay_state()
    local stable = count_stable_gate_tiles()
    local px = read_u8(0x6027)
    local py = read_u8(0x6028)
    return (px >= 0x00 and px <= 0xB0 and py >= 0x00 and py <= 0xD0 and stable >= 10)
end

local function enemy_slot_json(slot, base)
    local raw = read_u8(base)
    local dir = (raw >> 4) & 0x0f
    local collision_active = (raw & 0x02) ~= 0
    local bit0 = (raw & 0x01) ~= 0
    return obj({
        q("slot") .. ":" .. tostring(slot),
        q("addr") .. ":" .. q(h4(base)),
        q("raw") .. ":" .. q(h2(raw)),
        q("dir") .. ":" .. q(h2(dir)),
        q("bit0") .. ":" .. boolstr(bit0),
        q("collisionActive") .. ":" .. boolstr(collision_active),
        q("x") .. ":" .. q(h2(read_u8(base + 1))),
        q("y") .. ":" .. q(h2(read_u8(base + 2))),
        q("sprite") .. ":" .. q(h2(read_u8(base + 3))),
        q("attr") .. ":" .. q(h2(read_u8(base + 4)))
    })
end

local function enemies_json()
    return arr({
        enemy_slot_json(0, 0x602b),
        enemy_slot_json(1, 0x6030),
        enemy_slot_json(2, 0x6035),
        enemy_slot_json(3, 0x603a)
    })
end

local function player_json()
    return obj({
        q("raw") .. ":" .. q(h2(read_u8(0x6026))),
        q("x") .. ":" .. q(h2(read_u8(0x6027))),
        q("y") .. ":" .. q(h2(read_u8(0x6028))),
        q("sprite") .. ":" .. q(h2(read_u8(0x6029))),
        q("attr") .. ":" .. q(h2(read_u8(0x602a))),
        q("turnTargetX") .. ":" .. q(h2(read_u8(0x6196))),
        q("turnTargetY") .. ":" .. q(h2(read_u8(0x6197))),
        q("currentDir") .. ":" .. q(h2(read_u8(0x6198)))
    })
end

local function enemy_work_json()
    return obj({
        q("tempDir") .. ":" .. q(h2(read_u8(0x61bd))),
        q("tempX") .. ":" .. q(h2(read_u8(0x61be))),
        q("tempY") .. ":" .. q(h2(read_u8(0x61bf))),
        q("rejectedMask") .. ":" .. q(h2(read_u8(0x61c1))),
        q("fallbackMask") .. ":" .. q(h2(read_u8(0x61c2))),
        q("preferred") .. ":" .. arr({
            q(h2(read_u8(0x61c4))), q(h2(read_u8(0x61c5))),
            q(h2(read_u8(0x61c6))), q(h2(read_u8(0x61c7)))
        }),
        q("chaseTimers") .. ":" .. arr({
            q(h2(read_u8(0x61ce))), q(h2(read_u8(0x61cf))),
            q(h2(read_u8(0x61d0))), q(h2(read_u8(0x61d1)))
        }),
        q("chaseRoundRobin") .. ":" .. q(h2(read_u8(0x61d2)))
    })
end

local function timers_json()
    return obj({
        q("61B4") .. ":" .. q(h2(read_u8(0x61b4))),
        q("61B5") .. ":" .. q(h2(read_u8(0x61b5))),
        q("61B6") .. ":" .. q(h2(read_u8(0x61b6))),
        q("61B7") .. ":" .. q(h2(read_u8(0x61b7))),
        q("61B8") .. ":" .. q(h2(read_u8(0x61b8))),
        q("61B9") .. ":" .. q(h2(read_u8(0x61b9))),
        q("freeze61E1") .. ":" .. q(h2(read_u8(0x61e1))),
        q("collectibleColorCounter6199") .. ":" .. q(h4(read_u8(0x6199) + (read_u8(0x619a) << 8)))
    })
end

local function ports_json()
    return obj({
        q("in0_9000") .. ":" .. q(h2(read_u8(0x9000))),
        q("in1_9001") .. ":" .. q(h2(read_u8(0x9001))),
        q("dsw0_9002") .. ":" .. q(h2(read_u8(0x9002))),
        q("dsw1_9003") .. ":" .. q(h2(read_u8(0x9003)))
    })
end

local function frame_json(tick, phase)
    local fields = {
        q("schema") .. ":" .. q("ladybug.sequenceTrace.v7"),
        q("tick") .. ":" .. tostring(tick),
        q("phase") .. ":" .. q(phase),
        q("mameFrame") .. ":" .. tostring(mame_frame),
        q("pc") .. ":" .. q(state_hex({"CURPC", "PC", "rPC"}, 4)),
        q("r") .. ":" .. q(state_hex({"R", "rR", "IR"}, 2)),
        q("player") .. ":" .. player_json(),
        q("enemies") .. ":" .. enemies_json(),
        q("gates") .. ":" .. gates_json(false),
        q("enemyWork") .. ":" .. enemy_work_json(),
        q("timers") .. ":" .. timers_json(),
        q("ports") .. ":" .. ports_json()
    }

    if CONFIG.include_logical_maze_each_frame then
        fields[#fields + 1] = q("logicalMaze6200_62AF") .. ":" .. q(read_range_hex(0x6200, 0x00b0))
    end

    if CONFIG.include_full_memory_each_frame then
        fields[#fields + 1] = q("ram6000_62AF") .. ":" .. q(read_range_hex(0x6000, 0x02b0))
        fields[#fields + 1] = q("vramD000_D3FF") .. ":" .. q(read_range_hex(0xd000, 0x0400))
        fields[#fields + 1] = q("colorD400_D7FF") .. ":" .. q(read_range_hex(0xd400, 0x0400))
    end

    return obj(fields)
end

local function snapshot_json()
    local stable, horizontal, vertical, unknown = count_stable_gate_tiles()
    return obj({
        q("schema") .. ":" .. q("ladybug.sequenceInitialSnapshot.v7"),
        q("game") .. ":" .. q(emu.romname()),
        q("system") .. ":" .. q(emu.gamename()),
        q("mameVersion") .. ":" .. q(emu.app_name() .. " " .. emu.app_version()),
        q("saveStateRequested") .. ":" .. q(CONFIG.save_state or ""),
        q("captureOrigin") .. ":" .. q(capture_origin),
        q("tick0Meaning") .. ":" .. q("State captured immediately from emu.add_machine_post_load_notifier after save-state restore"),
        q("loadCallOk") .. ":" .. boolstr(load_call_ok == true),
        q("loadCallError") .. ":" .. q(load_call_error),
        q("framesSinceLoadRequestBeforePostLoad") .. ":" .. tostring(frames_since_load_request),
        q("loadLooksLikeGameplay") .. ":" .. boolstr(likely_gameplay_state()),
        q("stableGateTileCount") .. ":" .. tostring(stable),
        q("horizontalTile36Count") .. ":" .. tostring(horizontal),
        q("verticalTile3ECount") .. ":" .. tostring(vertical),
        q("unknownDoorTileCount") .. ":" .. tostring(unknown),
        q("mappingDiagnostics") .. ":" .. mapping_diagnostics_json(),
        q("gateMapping") .. ":" .. obj({
            q("source") .. ":" .. q("Arcade ROM table 0x0D1D for VRAM tile address, 0x46C4 for navigation-map index"),
            q("vramLayout") .. ":" .. q("D080..D3FF column-major, bottom-to-top"),
            q("pivotFormula") .. ":" .. q("column=floor((addr-D080)/0x20); row=(addr-D080)%0x20; GatePivot.x=floor((column-1)/2); GatePivot.y=floor((27-row)/2)"),
            q("stableTile36") .. ":" .. q("Horizontal"),
            q("stableTile3E") .. ":" .. q("Vertical")
        }),
        q("gates") .. ":" .. gates_json(true),
        q("player") .. ":" .. player_json(),
        q("enemies") .. ":" .. enemies_json(),
        q("enemyWork") .. ":" .. enemy_work_json(),
        q("timers") .. ":" .. timers_json(),
        q("ports") .. ":" .. ports_json(),
        q("ram6000_62AF") .. ":" .. q(read_range_hex(0x6000, 0x02b0)),
        q("logicalMaze6200_62AF") .. ":" .. q(read_range_hex(0x6200, 0x00b0)),
        q("vramD000_D3FF") .. ":" .. q(read_range_hex(0xd000, 0x0400)),
        q("colorD400_D7FF") .. ":" .. q(read_range_hex(0xd400, 0x0400)),
        q("tick0") .. ":" .. frame_json(0, "post_load_tick0")
    })
end

local function write_trace_line(tick, phase)
    if trace_file == nil then return end
    trace_file:write(frame_json(tick, phase) .. "\n")
    trace_lines_written = trace_lines_written + 1
    if CONFIG.flush_every_trace_line or trace_lines_written % 60 == 0 then trace_file:flush() end
end

local function finish_capture(reason)
    if done then return end
    done = true

    if summary_file ~= nil then
        summary_file:write("Lady Bug sequence v8 capture complete\n")
        summary_file:write("reason=" .. tostring(reason) .. "\n")
        summary_file:write("save_state=" .. tostring(CONFIG.save_state) .. "\n")
        summary_file:write("capture_origin=" .. tostring(capture_origin) .. "\n")
        summary_file:write("post_load_seen=" .. tostring(post_load_seen) .. "\n")
        summary_file:write("frames_since_load_request_before_post_load=" .. tostring(frames_since_load_request) .. "\n")
        summary_file:write("frames_after_tick0_written=" .. tostring(frames_after_tick0_written) .. "\n")
        summary_file:write("trace_lines_written=" .. tostring(trace_lines_written) .. "\n")
        summary_file:write("initial_snapshot_file=" .. output_path("_initial_snapshot.json") .. "\n")
        summary_file:write("trace_file=" .. output_path("_trace.jsonl") .. "\n")
    end

    close_outputs()
    local msg = "Lady Bug sequence v8 complete: " .. tostring(trace_lines_written) .. " trace lines"
    emu.print_info(msg)
    manager.machine:popmessage(msg)

    if CONFIG.pause_when_done then
        pcall(function() emu.pause() end)
        pcall(function() manager.ui.single_step = true end)
    end
    if CONFIG.exit_when_done then manager.machine:exit() end
end

local function initialize_if_needed()
    if initialized then return true end
    local ok, err = pcall(function()
        get_program_space()
        open_outputs_if_needed()
    end)
    if not ok then
        log_error("Lady Bug sequence v8: initialization failed: " .. tostring(err))
        done = true
        return false
    end
    initialized = true
    emu.print_info("Lady Bug sequence v8: initialized")
    return true
end

local function start_capture(origin)
    if capture_started or done then return end
    if not initialize_if_needed() then return end

    capture_origin = origin or "unknown"
    post_load_seen = (origin == "post_load") or post_load_seen
    capture_started = true

    snapshot_file:write(snapshot_json() .. "\n")
    snapshot_file:flush()

    -- First JSONL line is the exact post-load tick 0.
    write_trace_line(0, "post_load_tick0")
    emu.print_info("Lady Bug sequence v8: tick 0 captured from " .. capture_origin)
end

local function on_post_load()
    if done then return end
    if not initialize_if_needed() then return end
    post_load_seen = true
    emu.print_info("Lady Bug sequence v8: post-load notifier fired; starting trace at tick 0")
    start_capture("post_load")
end

local function request_load_if_needed()
    if load_requested then return end
    load_requested = true
    frames_since_load_request = 0

    if CONFIG.save_state ~= nil and CONFIG.save_state ~= "" then
        emu.print_info("Lady Bug sequence v8: requesting save-state load: " .. CONFIG.save_state)
        local ok, err = pcall(function() manager.machine:load(CONFIG.save_state) end)
        load_call_ok = ok
        if not ok then
            load_call_error = tostring(err)
            emu.print_error("Lady Bug sequence v8: save-state load call failed: " .. load_call_error)
            -- Fallback: capture without save-state, clearly labelled.
            start_capture("load_call_failed_fallback")
        end
    else
        load_call_ok = true
        emu.print_info("Lady Bug sequence v8: no save state requested; starting capture without load")
        start_capture("no_save_state")
    end
end

local function on_frame_done()
    if done then return end
    if not initialize_if_needed() then return end

    mame_frame = mame_frame + 1

    if not load_requested then
        if mame_frame >= CONFIG.load_after_frames then request_load_if_needed() end
        return
    end

    if not capture_started then
        frames_since_load_request = frames_since_load_request + 1
        -- Do not capture here. We wait for the real post-load notifier.
        -- If this grows a lot, the save-state probably was not found.
        if frames_since_load_request == 300 then
            emu.print_warning("Lady Bug sequence v8: still waiting for post-load notifier after 300 frames. Check save_state/state_directory/statename.")
        end
        return
    end

    -- Capture after each completed emulated frame following tick 0.
    if frames_after_tick0_written < CONFIG.frames_after_tick0_to_capture then
        frames_after_tick0_written = frames_after_tick0_written + 1
        write_trace_line(frames_after_tick0_written, "frame_done")

        if frames_after_tick0_written % 60 == 0 then
            trace_file:flush()
            manager.machine:popmessage("Lady Bug sequence v8: " .. tostring(frames_after_tick0_written) .. " / " .. tostring(CONFIG.frames_after_tick0_to_capture))
        end
    end

    if frames_after_tick0_written >= CONFIG.frames_after_tick0_to_capture then
        finish_capture("frames_after_tick0_limit_reached")
    end
end

if emu.add_machine_post_load_notifier ~= nil then
    post_load_subscription = emu.add_machine_post_load_notifier(on_post_load)
else
    emu.print_warning("Lady Bug sequence v8: emu.add_machine_post_load_notifier is not available; falling back to frame-based capture is disabled to avoid losing ticks.")
end

if emu.add_machine_reset_notifier ~= nil then
    reset_subscription = emu.add_machine_reset_notifier(function() initialize_if_needed() end)
end

-- In MAME 0.287, emu.add_machine_frame_notifier can be less convenient for this
-- use-case depending on machine lifecycle. register_frame_done is older but very
-- reliable here: it fires once after each emulated video frame, which is exactly
-- what we want for a deterministic trace.
if emu.register_frame_done ~= nil then
    emu.register_frame_done(on_frame_done, "ladybug_sequence_v7_frame_done")
elseif emu.add_machine_frame_notifier ~= nil then
    frame_subscription = emu.add_machine_frame_notifier(on_frame_done)
else
    error("No per-frame Lua callback available: neither emu.register_frame_done nor emu.add_machine_frame_notifier exists")
end
